Checking for updates...

 There is a update available for CheckLab5.py please consider updating:
 cd ~/ops435/lab5/
 pwd  #   <-- i.e. confirm that you are in the correct directory
 rm CheckLab5.py
 ls CheckLab5.py || wget https://ict.senecacollege.ca/~raymond.chan/ops435/labs/LabCheckScripts/CheckLab5.py

Press ENTER to run the Lab Check...cat: /etc/redhat-release: No such file or directory
test_0 (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for file creation: ./lab5a.py ... ok
test_a (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for errors running: ./lab5a.py ... ok
test_a1 (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for correct shebang line: ./lab5a.py ... ok
test_a1_author_id (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Correct Script ID - match system ID: ./lab5a.py ... ok
test_a_function_read_file_string (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - function read_file_string fails without 1 argument ... ok
test_b_function_read_file_list (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - function read_file_list fails without 1 argument ... ok
test_c_file_data_txt_exists (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for file creation: ./data.txt ... ok
test_d_file_data_txt_has_correct_text (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for correct contents: ./data.txt ... ok
test_e_function_read_file_string_correct_output (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_f_function_read_file_list_correct_output (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_g_function_read_file_list_correct_output (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_h_function_read_file_list_correct_output (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_0 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for file creation: ./lab5b.py ... ok
test_a (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for errors running: ./lab5b.py ... ok
test_a1 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for correct shebang line: ./lab5b.py ... ok
test_a1_author_id (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Correct Script ID - match system ID: ./lab5b.py ... ok
test_a_function_append_file_string (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function append_file_string fails without 2 argument ... ok
test_a_function_read_file_string (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function read_file_string fails without 1 argument ... ok
test_b_function_read_file_list (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function read_file_list fails without 1 argument ... ok
test_c_function_write_file_list (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function write_file_list fails without 2 argument ... ok
test_d_function_copy_file_add_line_numbers (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function copy_file_add_line_numbers fails without 2 argument ... ok
test_e_file_data_txt_exists (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for file creation: ./data.txt ... ok
test_f_file_data_txt_has_correct_text (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for correct contents: ./data.txt ... ok
test_g_function_read_file_string_correct_output (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ok
test_h_function_read_file_list_correct_output (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ok
test_i_function_append_file_string_correct_output_1 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ok
test_i_function_append_file_string_correct_output_2 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ok
test_j_function_write_file_list_correct_output_1 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ok
test_j_function_write_file_list_correct_output_2 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ok
test_k_function_copy_file_add_line_numbers_correct_output_1 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ./CheckLab5.py:321: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='r' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./CheckLab5.py:321: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='w' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_k_function_copy_file_add_line_numbers_correct_output_2 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ./CheckLab5.py:336: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='r' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./CheckLab5.py:336: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='w' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./CheckLab5.py:337: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='r' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./CheckLab5.py:337: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='w' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_k_function_copy_file_add_line_numbers_correct_output_3 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ./CheckLab5.py:350: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='r' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./CheckLab5.py:350: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca4.txt.checkscript' mode='w' encoding='UTF-8'>
  lab5bStudent.copy_file_add_line_numbers(filename, tempfile)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_0 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for file creation: ./lab5c.py ... ok
test_a (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for errors running: ./lab5c.py ... ok
test_a1 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for correct shebang line: ./lab5c.py ... ok
test_a1_author_id (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Correct Script ID - match system ID: ./lab5c.py ... ok
test_a_function_add (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - function add fails without 2 argument ... ok
test_b_function_read_file (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - function read_file fails without 1 argument ... ok
test_c_function_add_correct_output_1 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_c_function_add_correct_output_2 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_c_function_add_correct_output_3 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_c_function_add_correct_output_4 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_d_function_read_file_correct_output_1 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_d_function_read_file_correct_output_2 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok

----------------------------------------------------------------------
Ran 44 tests in 0.168s

OK
OPS435 Lab Report - System Information for running ./CheckLab5.py
=================================================================
    User login name: 1000
    Linux system name: DESKTOP-NDKH9N8
    Linux system version: 
    Python executable: /usr/bin/python3
    Python version: 385
    OS Platform: linux
    Working Directory: /mnt/c/ops435/lab5
    Start at: Sat Jan  2 17:37:54 2021
=================================================================
